"""000_initial_schema

Revision ID: 000
Revises: 
Create Date: 2025-06-26 19:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('auth_provider_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('doctor', 'nurse', 'pharmacist', 'super_admin', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_auth_provider_id'), 'users', ['auth_provider_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('drugs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=False),
    sa.Column('strength', sa.String(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'form', 'strength')
    )
    op.create_index(op.f('ix_drugs_id'), 'drugs', ['id'], unique=False)
    op.create_table('wards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'hospital_id')
    )
    op.create_index(op.f('ix_wards_hospital_id'), 'wards', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_wards_id'), 'wards', ['id'], unique=False)
    op.create_index(op.f('ix_wards_name'), 'wards', ['name'], unique=False)
    op.create_table('drug_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('source_ward', sa.String(), nullable=False),
    sa.Column('destination_ward', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), nullable=False),
    sa.Column('transfer_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_transfers_drug_id'), 'drug_transfers', ['drug_id'], unique=False)
    op.create_index(op.f('ix_drug_transfers_id'), 'drug_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_drug_transfers_pharmacist_id'), 'drug_transfers', ['pharmacist_id'], unique=False)
    op.create_table('medication_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('dosage', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'discontinued', name='orderstatus'), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_orders_doctor_id'), 'medication_orders', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medication_orders_drug_id'), 'medication_orders', ['drug_id'], unique=False)
    op.create_index(op.f('ix_medication_orders_id'), 'medication_orders', ['id'], unique=False)
    op.create_index(op.f('ix_medication_orders_status'), 'medication_orders', ['status'], unique=False)
    op.create_table('user_ward_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('doctor', 'nurse', 'pharmacist', 'super_admin', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ward_id')
    )
    op.create_index(op.f('ix_user_ward_permissions_id'), 'user_ward_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_user_ward_permissions_user_id'), 'user_ward_permissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_ward_permissions_ward_id'), 'user_ward_permissions', ['ward_id'], unique=False)
    op.create_table('medication_administrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('administration_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['medication_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_administrations_id'), 'medication_administrations', ['id'], unique=False)
    op.create_index(op.f('ix_medication_administrations_nurse_id'), 'medication_administrations', ['nurse_id'], unique=False)
    op.create_index(op.f('ix_medication_administrations_order_id'), 'medication_administrations', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_administrations_order_id'), table_name='medication_administrations')
    op.drop_index(op.f('ix_medication_administrations_nurse_id'), table_name='medication_administrations')
    op.drop_index(op.f('ix_medication_administrations_id'), table_name='medication_administrations')
    op.drop_table('medication_administrations')
    op.drop_index(op.f('ix_user_ward_permissions_ward_id'), table_name='user_ward_permissions')
    op.drop_index(op.f('ix_user_ward_permissions_user_id'), table_name='user_ward_permissions')
    op.drop_index(op.f('ix_user_ward_permissions_id'), table_name='user_ward_permissions')
    op.drop_table('user_ward_permissions')
    op.drop_index(op.f('ix_medication_orders_status'), table_name='medication_orders')
    op.drop_index(op.f('ix_medication_orders_id'), table_name='medication_orders')
    op.drop_index(op.f('ix_medication_orders_drug_id'), table_name='medication_orders')
    op.drop_index(op.f('ix_medication_orders_doctor_id'), table_name='medication_orders')
    op.drop_table('medication_orders')
    op.drop_index(op.f('ix_drug_transfers_pharmacist_id'), table_name='drug_transfers')
    op.drop_index(op.f('ix_drug_transfers_id'), table_name='drug_transfers')
    op.drop_index(op.f('ix_drug_transfers_drug_id'), table_name='drug_transfers')
    op.drop_table('drug_transfers')
    op.drop_index(op.f('ix_wards_name'), table_name='wards')
    op.drop_index(op.f('ix_wards_id'), table_name='wards')
    op.drop_index(op.f('ix_wards_hospital_id'), table_name='wards')
    op.drop_table('wards')
    op.drop_index(op.f('ix_drugs_id'), table_name='drugs')
    op.drop_table('drugs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_provider_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ### 